version: 0.2

env:
  variables:
    TF_VAR_bucket_name: "deepak-s3-bucket-2026-terraform"
    TF_VAR_my_name: "Deepak"
    TF_VAR_region: "ap-south-1"

phases:
  install:
    commands:
      - yum install -y unzip curl
      - curl -O https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip terraform_1.5.7_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version
  pre_build:
    commands:
      - rm -rf .terraform
  build:
    commands:
      - terraform init
      - terraform plan -out=tfplan
  post_build:
    commands:
      - echo "Plan complete."

artifacts:
  files:
    - tfplan
